// src/routes/[lang]/(website)/trophy/+page.svelte
<script>
  import trophyImage from '$lib/assets/website/trophy-128.png'
  import { page } from '$app/stores'

  export let data
</script>

<section class='hero'>
  <h1>Трофеи</h1>
  <h2>Столько всего можно сделать...</h2>
</section>

<section class='trophies'>
  {#each data.trophies as trophy}
    <a href='/{$page.data.locale}/trophy/{trophy.id}'>
      <div class='trophy-block'>
        <div class='info'>
          <p class='name'>{trophy.name}</p>
          <p class='description'>{trophy.description}</p>
        </div>
        <div class='completion'>
          <div class='trophy'>
            <img src={trophyImage} alt="" width='64' height='64' />
          </div>
          <div>
            <p class='points'>{trophy.points}</p>
            <p>Очков</p>
          </div>
        </div>
      </div>
    </a>
  {/each}
</section>

<style>
    .hero {
        padding-top: 4em;
        padding-bottom: 4em;
        max-width: 64em;
    }

    .hero h1 {
        margin-bottom: 0.25em;
    }

    section {
        text-align: center;
        padding: 2em 1em;
        margin: 0 auto;
        max-width: 42em;
    }

    .trophies a {
      text-decoration: none;
      color: inherit;
    }

    .trophy-block {
      background-color: #FFEFD6;
      border: 2px solid var(--color-border);
      display: grid;
      grid-template-columns: 2fr 1fr;
      margin-bottom: 0.5em;
      transition: all 0.2s;
    }

    .trophy-block:hover {
      transform: scale(0.98);
    }

    .trophy-block .info {
      position: relative;
      padding: 0.5em 1em;
    }

    .trophy-block .info .name {
      font-weight: 600;
      font-size: 1.1rem;
      opacity: 0.8;
    }

    .trophy-block .info .description {
      font-size: 0.9rem;
    }

    .trophy-block .completion {
      position: relative;
      padding: 0.5em 1em;
      color: #F76B15;
      display: flex;
      flex-direction: row;
      flex-wrap: nowrap;
      align-items: center;
      justify-content: center;
      gap: 0.5em;
    }

    .trophy-block .completion .points {
      font-size: 1.5rem;
      font-weight: 600;
      line-height: 1.2;
    }

    .trophy-block .completion .trophy {
      opacity: 1;
    }
</style>

// apps/website/app/pages/trophy/index.vue
<template>
  <section class="hero">
    <h1>Трофеи</h1>
    <h2>Придумываем вместе награды за особые активности на стримах</h2>

    <div class="create-new">
      <NuxtLink :to="localePath('/trophy/new')">
        Создать новый <img src="~/assets/img/icons/mana/64.png" alt="" width="32" height="32">
      </NuxtLink>
    </div>
  </section>

  <section class="trophies-block">
    <div class="trophies">
      <div v-for="trophy in trophies" :key="trophy.id" class="cell" :data-rarity="trophy.rarity">
        <NuxtLink :to="localePath(`/trophy/${trophy.id}`)">
          <img src="/trophies/default/64.png" alt="" width="64" height="64">
          <div class="name">
            {{ trophy.name }}
          </div>
          <div class="points">
            {{ trophy.points }} очков
          </div>
        </NuxtLink>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
const localePath = useLocalePath()
const { data: trophies } = await useFetch('/api/trophy/')
</script>

<style scoped>
  .create-new {
    position: relative;
    margin-top: 1em;
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;

    a {
      display: flex;
      flex-direction: row;
      align-items: center;
      justify-content: center;
      gap: 0.75em;
      padding: 0.75em 1.5em;
      border: 3px solid var(--bronze-6);
      background-color: var(--orange-9);
      background: linear-gradient(130deg, var(--blue-11) 0%, var(--blue-8) 100%);
      color: var(--orange-2);
      font-weight: 600;
      transition: all 0.2s;

      &:hover {
        text-decoration: none;
        scale: 1.03;
      }
    }
  }

  .trophies-block {
    max-width: 64em;
    margin: 0 auto;

    h2 {
      margin-bottom: 1em;
    }

    .trophies {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 0.5em;

      @media (min-width: 375px) {
        grid-template-columns: repeat(3, 1fr);
      }

      @media (min-width: 620px) {
        grid-template-columns: repeat(3, 1fr);
        gap: 0.75em;
      }

      @media (min-width: 768px) {
        grid-template-columns: repeat(4, 1fr);
      }

      @media (min-width: 1024px) {
        grid-template-columns: repeat(6, 1fr);
      }
    }

    .cell {
      position: relative;
      aspect-ratio: 1 / 1;
      transition: all 0.2s ease-out;
      padding: 0.5em;

      &[data-rarity='0'] {
        background: var(--gray-4);
        border: 3px solid var(--gray-8);
        color: var(--gray-11);
      }

      &[data-rarity='1'] {
        background: var(--green-4);
        border: 3px solid var(--green-7);
        color: var(--green-11);
      }

      &[data-rarity='2'] {
        background: var(--blue-4);
        border: 3px solid var(--blue-7);
        color: var(--blue-11);
      }

      &[data-rarity='3'] {
        background: var(--purple-4);
        border: 3px solid var(--purple-7);
        color: var(--purple-11);
      }

      &[data-rarity='4'] {
        background: var(--orange-4);
        border: 3px solid var(--orange-7);
        color: var(--orange-11);
      }

      img {
        width: 48px;
        height: 48px;
        margin-bottom: 0.5em;
      }

      &:hover {
        transform: translateY(-0.25em);
      }

      a {
        text-decoration: none;
        color: inherit;
        width: 100%;
        height: 100%;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
      }

      .name {
        font-size: 1rem;
        font-weight: 600;
        line-height: 1;
        min-height: 2.25em;
        display: flex;
        flex-direction: column;
        align-items: start;
        justify-content: start;
      }

      .points {
        margin-top: 0.35em;
        font-size: 0.9rem;
        font-weight: 600;
        line-height: 1;
      }
    }
  }
</style>
